In [1]:
import numpy as np
from numpy.linalg import solve

In [28]:
#初期設定
K = [2, 1]
m = [2, 1, 0] #Node3はIS(Infinite server)
mu = np.array([[5.0, 5.0], [5/2, 5/3], [1, 0.5]])
alpha = np.array([[1.0, 1.0], [0.6, 0.3], [0.4, 0.7]])

#2022/07/11 状態算出 (今回は3進数2桁)
max_state_number = max(K) * (max(K) + 1)**1 + max(K) * (max(K) + 1)**0
max_state_number

L = np.zeros((3,2,max_state_number))
T = np.zeros((3,2,max_state_number))
Lambda = np.zeros((len(K)))
#L = np.zeros((3,2,3,2))
#T = np.zeros((3,2,3,2))
#Lambda = np.zeros((2))

In [29]:
def getPi(n, j, k, kr):
  kkr = k - kr #指定クラスを1引いたもの
  if min(kkr) < 0:
    return 0
  if j == 0 and sum(kkr) == 0:
    return 1

In [30]:
def getState_kr(K, k, kr):
  state = 0
  kkr = k - kr
  if min(kkr) < 0:
    return -1
  else:
    for i in range(len(k)):
      state += k[i] * (max(K) + 1)**int(len(k)-1-i)
    return state

In [31]:
def getState(K, k):
  state = 0
  for i in range(len(k)):
    state += k[i] * (max(K) + 1)**int(len(k)-1-i)
  return state

In [32]:
def getL(n, r, state_number):
  if state_number >= 0:
    return L[n,r,state_number]
  else:
    return 0

In [33]:
k = np.array([1, 0])

for r in range(len(K)):

  state_number = getState(K, k)
  kr = np.zeros(len(k))
  kr[r] += 1
  kr_state_number = int(getState_kr(K, k, kr))
  print(kr_state_number)

  if kr_state_number < 0:
    for n in range(len(m)):
      T[n,r,state_number] = 0
  else:
    for n in range(len(m)): # r = 0
      if m[n] >= 1:
        sum_L = 0
        for _r in range(len(K)): #Lの和の部分を計算
          sum_L += getL(n, _r, kr_state_number)
        T[n,r,state_number] = 1 / (m[n] * mu[n,r]) * (1 + sum_L)
        if m[n] > 1:
          sum_pi = 0
          for _j in range(m[n]-2+1):
            sum_pi += getPi(n, _j, k, kr) 
          T[n,r,state_number] += 1 / (m[n] * mu[n,r]) * sum_pi
          #T[n,r,state_number] += 1 / (m[n] * mu[n,r]) * getPi(n, 0, k, kr) #この0は一般化する
      #if m[n] > 1:
      #  T[n,r,state_number] = 1 / (m[n] * mu[n,r]) * (1 + getL(n,0,kr_state_number) + getL(n,1,kr_state_number) + getPi(n, 0, k, kr)) #getLの和を作成
      #if m[n] == 1:
      #  T[n,r,state_number] = 1 / (m[n] * mu[n,r]) * (1 + getL(n,0,kr_state_number) + getL(n,1,kr_state_number)) 
      if m[n] == 0:
        T[n,r,state_number] = 1 / mu[n,r]   


#r = 1
#kr = np.zeros(len(k))
#kr[r] += 1
#print(k - kr)
#print(min(k - kr))
#kr_state_number = int(getState_kr(K, k, kr))
#print(kr_state_number)
#k - krを実施して、最小値が負になる場合は計算をしないようにする

#if kr_state_number < 0:
#  for n in range(len(m)):
#    T[n,1,state_number] = 0
#else: 
#  for n in range(len(m)): 
#    if m[n] > 1:
#      T[n,1,state_number] = 1 / (m[n] * mu[n,1]) * (1 + getL(n,0,kr_state_number) + getL(n,1,kr_state_number) + getPi(n, 0, k, kr))
#    if m[n] == 1:
#      T[n,1,state_number] = 1 / (m[n] * mu[n,1]) * (1 + getL(n,0,kr_state_number) + getL(n,1,kr_state_number)) 
#    if m[n] == 0:
#      T[n,1,state_number] = 1 / mu[n,1]   


#for n in range(len(m)):
#  if m[n] > 1:
#    T[n,0,1,0] = 1 / (m[n] * mu[n,0]) * (1 + L[n,0,1-1,0] + L[n,1,1-1,0] + getPi(n, 0, [0, 0]))
#  if m[n] == 1:
#    T[n,0,1,0] = 1 / (m[n] * mu[n,0]) * (1 + L[n,0,1-1,0] + L[n,1,1-1,0]) 
#  if m[n] == 0:
#    T[n,0,1,0] = 1 / mu[n,0]   
#T[1,0,1,0] = 1 / (m[1] * mu[1,0]) * (1 + L[1,0,1-1,0] + L[1,1,1-1,0])
#T[2,0,1,0] = 1 / mu[2,0]
T

3
-1


array([[[0. , 0. , 0. , 0.2, 0. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ]],

       [[0. , 0. , 0. , 0.4, 0. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ]],

       [[0. , 0. , 0. , 1. , 0. , 0. , 0. , 0. ],
        [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ]]])

In [34]:
#Step2.2
et = 0
for i in range(len(m)):
  et += alpha[i,0] * T[i,0,state_number]
  #et += alpha[i,0] * T[i,0,1,0]
Lambda[0] = k[0] / et
#Lambda[0] = k[0] / (alpha[0,0] * T[0,0,1,0] + alpha[1,0] * T[1,0,1,0] + alpha[2,0] * T[2,0,1,0])
Lambda[0]

1.1904761904761905

In [35]:
#Step2.3
L[0,0,state_number] = Lambda[0] * T[0,0,state_number] * alpha[0,0]
L[1,0,state_number] = Lambda[0] * T[1,0,state_number] * alpha[1,0]
L[2,0,state_number] = Lambda[0] * T[2,0,state_number] * alpha[2,0]

#L[0,0,1,0] = Lambda[0] * T[0,0,1,0] * alpha[0,0]
#L[1,0,1,0] = Lambda[0] * T[1,0,1,0] * alpha[1,0]
#L[2,0,1,0] = Lambda[0] * T[2,0,1,0] * alpha[2,0]
L

array([[[0.        , 0.        , 0.        , 0.23809524, 0.        ,
         0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        ]],

       [[0.        , 0.        , 0.        , 0.28571429, 0.        ,
         0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        ]],

       [[0.        , 0.        , 0.        , 0.47619048, 0.        ,
         0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        ]]])

In [36]:
k = np.array([0, 1])
for r in range(len(K)):
  state_number = getState(K, k)
  kr = np.zeros(len(k))
  kr[r] += 1
  kr_state_number = int(getState_kr(K, k, kr))
  print(kr_state_number)

  if kr_state_number < 0:
    for n in range(len(m)):
      T[n,r,state_number] = 0
  else:
    for n in range(len(m)): 
      if m[n] >= 1:
        sum_L = 0
        for _r in range(len(K)): #Lの和の部分を計算
          sum_L += getL(n, _r, kr_state_number)
        T[n,r,state_number] = 1 / (m[n] * mu[n,r]) * (1 + sum_L)
        if m[n] > 1:
          sum_pi = 0
          for _j in range(m[n]-2+1):
            sum_pi += getPi(n, _j, k, kr) 
          T[n,r,state_number] += 1 / (m[n] * mu[n,r]) * sum_pi
      if m[n] == 0:
        T[n,r,state_number] = 1 / mu[n,r]   
T

-1
1


array([[[0. , 0. , 0. , 0.2, 0. , 0. , 0. , 0. ],
        [0. , 0.2, 0. , 0. , 0. , 0. , 0. , 0. ]],

       [[0. , 0. , 0. , 0.4, 0. , 0. , 0. , 0. ],
        [0. , 0.6, 0. , 0. , 0. , 0. , 0. , 0. ]],

       [[0. , 0. , 0. , 1. , 0. , 0. , 0. , 0. ],
        [0. , 2. , 0. , 0. , 0. , 0. , 0. , 0. ]]])

In [38]:
#k = [0, 1]
#state_number = k[0] * (max(K) + 1)**1 + k[1] * (max(K) + 1)**0
#print(state_number)

#for n in range(len(m)):
#  if m[n] > 1:
#    T[n,1,state_number] = 1 / (m[n] * mu[n,1]) * (1 + L[n,0,0] + L[n,1,0] + getPi(n, 0, [0, 0]))
#  if m[n] == 1:
#    T[n,1,state_number] = 1 / (m[n] * mu[n,1]) * (1 + L[n,0,0] + L[n,1,0]) 
#  if m[n] == 0:
#    T[n,1,state_number] = 1 / mu[n,1]


#for n in range(len(m)):
#  if m[n] > 1:
#    T[n,1,0,1] = 1 / (m[n] * mu[n,1]) * (1 + L[n,0,0,1-1] + L[n,1,0,1-1] + getPi(n, 0, [0, 0]))
#  if m[n] == 1:
#    T[n,1,0,1] = 1 / (m[n] * mu[n,1]) * (1 + L[n,0,0,1-1] + L[n,1,0,1-1]) 
#  if m[n] == 0:
#    T[n,1,0,1] = 1 / mu[n,1]
#T

In [39]:
#Step2.2
et = 0
for i in range(len(m)):
  et += alpha[i,1] * T[i,1,state_number]
  #et += alpha[i,1] * T[i,1,0,1]
Lambda[1] = k[1] / et
#Lambda[0] = k[0] / (alpha[0,0] * T[0,0,1,0] + alpha[1,0] * T[1,0,1,0] + alpha[2,0] * T[2,0,1,0])
Lambda[1]

0.5617977528089888

In [40]:
#Step2.3
L[0,1,state_number] = Lambda[1] * T[0,1,state_number] * alpha[0,1]
L[1,1,state_number] = Lambda[1] * T[1,1,state_number] * alpha[1,1]
L[2,1,state_number] = Lambda[1] * T[2,1,state_number] * alpha[2,1]

#L[0,1,1,0] = Lambda[1] * T[0,1,0,1] * alpha[0,1]
#L[1,1,1,0] = Lambda[1] * T[1,1,0,1] * alpha[1,1]
#L[2,1,1,0] = Lambda[1] * T[2,1,0,1] * alpha[2,1]
L

array([[[0.        , 0.        , 0.        , 0.23809524, 0.        ,
         0.        , 0.        , 0.        ],
        [0.        , 0.11235955, 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        ]],

       [[0.        , 0.        , 0.        , 0.28571429, 0.        ,
         0.        , 0.        , 0.        ],
        [0.        , 0.1011236 , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        ]],

       [[0.        , 0.        , 0.        , 0.47619048, 0.        ,
         0.        , 0.        , 0.        ],
        [0.        , 0.78651685, 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        ]]])

In [ ]:
k = np.array([1,1])
kr = np.array([0,1])
k - kr
